### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [MateuszKrasinski/Gomoku#1]
Projekt całkiem nieźle się prezentuje. Jeśli AI działa, to po uwzględnieniu uwag i dopisaniu testów będzie po wszystkim.

1. `opis_Gomoku.md` lepiej przenieść do `README.md`.
2. W `ai.py` dodać pusty wiersz między importami a stałymi (czy pylintowi się podoba tak, jak jest teraz?)
3. Magiczne stałe `"black"`, `"white"` i `"_"` zastąpić przez `EMPTY, BLACK, WHITE = range(3)` (*vide* 2. rozdział Poradnika).
4. Atrybut `b` klasy `Game` ma niezrozumiałą nazwę (czy pylint go łyknął?).

**Comment by MateuszKrasinski** [comment]
Zmiany zostały wprowadzone.
Projekt gotowy do oceny.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Oto kolejna porcja uwag.
1. [Proszę przeczytać punkt o antywzorcach pętli z 3. rozdziału](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/ai.py#L66).
2. [Zbędne nawiasy](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/ai.py#L204).
3. [Wolę `operator.itemgetter()`](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/ai.py#L210).
4. Niedobre jest powtarzanie `BOARD_SIZE = 15`, `BOARDSIZE = 15` itp. stałych w różnych modułach.
5. Czy [tutaj](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/game.py#L39) dałoby się przekazywać graczy z zewnątrz (4. rozdział)? Dzięki temu można by grać białymi albo czarnymi, a nawet we dwóch ludzkich graczy, prawda? Wolałbym dwie klasy: `HumanPlayer` i `ComputerPlayer`, dziedziczące co trzeba z `PlayerBase`. Ta druga mogłaby wciągnąć dotychczasową klasę `AI`, której tworzenie luzem w `Game`, oderwanej od gracza, który jej używa, jest nieładne.
6. W `Game` do `.played_moves` i `.last_move` lepsze będzie `collections.namedtuple`.
7. [Albo spacje, albo przecinki](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/main.py#L14).
8. W `main.py` nie ma funkcji `main()`. Luźno lewitujący kod włożyć do funkcji. Zamiast `if ...: continue; break` lepiej `if not ...: break`.
9. [`(BOARD_SIZE - 1) // 2 - 1, (BOARD_SIZE - 1) // 2 + 1`](https://github.com/MateuszKrasinski/Gomoku/blob/fcc7a66f71cf7993cc3a3dbf0b25a390ebf45ffa/swap2.py#L40).
10. `test_check_board_state.py` przemianować na `check_board_state_test.py` i powyrzucać `self.setUp()` z metod.

**Comment by MateuszKrasinski** [comment]
Dziękuj za uwagi.
Zmiany zostały wprowadzone.
Stworzyłem klasy PlayerBase, AiPlayer, HumanPlayer i przeniosłem do modułu players.py , a moduł ai został do tego modułu wciągnięty.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Jesteśmy blisko zakończenia.

1. [Bez obciachu](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/check_board_state.py#L108) (koniec 2. rozdziału Poradnika).
2. [To się powtarza w testach](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/game.py#L22). Zrobić z tego gdzieś malutką funkcję pomocniczą.
3. [Przeczytać punkt o skutkach ubocznych importowania modułów w 3. rozdziale](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/gui.py#L42).
4. [Tu też](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/gui.py#L29). Najszybszy sposób to przeniesienie `screen = ...` do `main()` i przekazywanie do tych 2 funkcji, które go potrzebują.
5. [Zbędne `()`](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/gui.py#L160).
6. [Zbędny `pass`](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/players.py#L27). Sam docstring wystarcza. Jak Pan chce, można dać `raise NotImplementedError`.
7. Proszę zauważyć, że [to](https://github.com/MateuszKrasinski/Gomoku/blob/222a69b447d409ac3b1096845607ec2e67e53e27/main.py#L11) jest zupełnie nieużywane. Powinno być w `game.py`, gdzie `.menu()` powinno zwracać `GameSettings(player1=..., player2=..., ...)` zamiast krotki, w której indeksy są magiczne, i w `main()` używać `settings.mode` itp. (`game_` jest zbędne) zamiast `game_settings[3]` itp.

**Comment by MateuszKrasinski** [comment]
[Stworzyłem funkcje pomocniczą w check_board_state.py  i wywołuje ją w testach tego modułu i konstruktorze klasy Game.
Moduł gui.py wciągnąłem w klase bazową Gui, gdzie przez konstruktor jest przekazywany screen utworzony w mainie. Pozostałem klasy, które znajdowały sie w tym module dziedzicą screen po klasie Gui.
GameSettings zostało przeniosione do game.py i używane w momencie returna  z .menu do maina.
Dziękuje za uwagi.

**Comment by MarcinCiura** [comment]
Proszę jeszcze zerknąć na te trzy uwagi.
1. Z [tego](https://github.com/MateuszKrasinski/Gomoku/blob/69254383d482cca6acaba7c29d716f193b746ffa/swap2.py#L15) wiersza wnoszę, że nie puszczał Pan ostatnio pylinta.
2. [Tu](https://github.com/MateuszKrasinski/Gomoku/blob/69254383d482cca6acaba7c29d716f193b746ffa/swap2.py#L17) w Pythonie 3 wystarczy `super().__init__(screen)`.
3. Gdzieś chyba przepadło `pygame.init()`.

**Comment by MateuszKrasinski** [comment]
Dziękuję za uwagi.
1.Pylint nie zgłasza zastrzeżeń co do tej linijki
2.Wszystkie miejsca w kodzie z  super().__init zostały zamienione.
3. pygame.init() zostało dodane na początku maina.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję pracowitości, jest Pan pierwszy.

**Comment by MateuszKrasinski** [comment]
Super!
Dziękuję bardzo za rady :D
